### PR TITLE
Lecture3

### PR DESCRIPTION
**Pull request by nozzington**
Lecture 3 and images, vectors fixed and made into bold face. hopefully this works, anything wrong I will fix.

### CODE REVIEW

**Comment by angadhn** [comment]
@thedukeofeelam can you please help review this PR?

**Comment by thedukeofeelam** [comment]
@nozzington, lol it must be annoying hearing from me again, I'll keep this short. 

1) Your level 1 heading is currently "#Lecture 3", replace this with "#nameOfLecture". Here's the textbook so far, make sure your new heading is not something that already exists on there: https://www.angadhn.com/SpacecraftDynamics/orbital-mechanics/Lecture4/Lecture4.html

2) Insert a cell for credits just like in the other lecture: 

image

3) Add "In this lecture we aim to cover the following topics:" before the contents table 
4) Code your contents table this way:

image

5) And ensure, you have this piece of code before each of your level 2 headings. This ensures the hyperlinks work as intended.

image

6) The main equations (which will require an equation number) must be coded this way:

image
* Again here, L4_3 refers to equation 3 of lecture 4. In your lecture, this would be "L3_xyz"

7) Do you really want this to be red? I think for consistency's sake, leave it in black. 

image 

If you want to make it clearer that the red part is coming from the previous equation, then you can reference that equation within the text body like this: "The velocity vector (Equation {eq}`L3_xyz`) is crossed with the specific angular momentum vector, $\mathbf{h}$ as here:" or something along that line. 

8) Brackets may be made to look nicer using ChatGPT: 

image
*is that = sign necessary there? 

is turned into: 

image

9) If my memory server right, this should not be in bold:

image

10) Likewise, check if this is correct? Maybe one one the e's should not be in bold? 

image

11) The section on the equation of the orbit gets rendered this way:

image

This must be due to the spacing of the equations in your ipynb. Ensure it's all neat and perhaps has a spacing before after the double dollars. Tbh, you are going to turn most of the equations using point (6). 

12) Elliptic Orbits figure does not get rendered on the HTML page: 

image

Code it this way:

image

* the yellow highlight is your path to the image file. Note, your image is a PNG so ensure the extension is correct. And give it a good figure caption (without including "Figure 1:" as that gets automatically generated). So if you did that right, when you click run, you will see something like this on your local notebook (but it will render just perfectly in the final textbook!):  

image

13) Use of colours, I'll let @angadhn decide on this. Maybe you can dump this section on what each letter means inside the figure caption. 

image

14) The next tiny section on key parameters renders on HTML this way: 

image

Again, the dollars pop up because you didn't leave spaces before the equations on two of them:

image

But reminder, you will be formatting the equations as noted in point (6).

15) Your next section: same issues as previously discussed:

image

16) Since Vis Viva is pretty vital, maybe you can make a reference to the equation here:

image

"The Vis Viva equation ({eq}`L3_xyz`) is a crucial tool in mission planning for calculating velocities at various points in an orbit."

**Comment by thedukeofeelam** [comment]
I just realised, the equation referencing gets rendered in my comments above (points 7 and 15). But the code behind referencing an equation looks like this: 

image

**Comment by angadhn** [comment]
@nozzington is this ready for review again by @thedukeofeelam and me?

**Comment by thedukeofeelam** [comment]
@angadhn I believe Noah is still working on it - he's made some updates and has called a commit for those changes. 

@nozzington, here is a PDF of the HTML page. I've added a couple of notes on there too. Essentially, work your way through yesterday's review points (and read the few points in red on the PDF too). 

[Lecture3.pdf](https://github.com/user-attachments/files/16868400/Lecture3.pdf)

**Comment by nozzington** [comment]
this should now be ready for review, if there are any issues I can fix again tonight

**Comment by thedukeofeelam** [comment]
> this should now be ready for review, if there are any issues I can fix again tonight

Alrighty. I am going to review them again in a bit and let you know before you start working on it again tonight.

**Comment by thedukeofeelam** [comment]
1)  Bolden this 'c'

image

2) Rogue $$

image

3) This section renders this way:

**Comment by thedukeofeelam** [comment]
1)  Bolden this 'c'

image

2) Rogue $$

image

That $$ needs to be replaced with: ``` as here:

image

3) This section renders this way:

image

Leave a space like this in the markup to address that:

image

4) Brackets around the theta here:

image

5) This is what you have for the image code:

image

This is what you should have (note the subtle spaces + dashes instead of the colon like character in some places + also make PNG lowercase):

image

6) Brackets in these three places are unnecessary - the automatic referencing gives you references like (6) and (7), so no need for additional bracketing. 

image
image

7) The most important bit now:  In every major equation that you have, there is no space after the colon there and so the HTML doesn't give you auto-labelling. Make sure in all 10 of your major equations, there is that single space after the colon.

image

**Comment by nozzington** [comment]
have addressed all points, let me know if anything else is wrong!

**Comment by thedukeofeelam** [comment]
> @thedukeofeelam have addressed all points, let me know if anything else is wrong!
> 

Thanks Noah! Will take a look first thing in the morning, and hopefully we can have these both merged before the end of today. Goodnighty.

**Comment by thedukeofeelam** [comment]
1) The first equation doesn't get recognised, because again the space between the colon and L3_1 is missing in this particular equation
2) fix the alignment issue here. Just tab those certain lines to the right by 1 level

image

3) Add a space after "(18)"

image

4) While you are at it, just increase the width from 50% to maybe like 75 or 80%. Careful here, don't forget the spaces, otherwise we will have to do another commit haha. 

image

Otherwise, everything is perfect in this lecture. @nozzington

**Comment by nozzington** [comment]
@thedukeofeelam hopefully this is finally done

**Comment by thedukeofeelam** [comment]
> @thedukeofeelam hopefully this is finally done
> 

*Doing a little prayer 😂*

Im away from my laptop, but yup make those commits for the two lectures, will review in the morning and update. Thanks Noah.

**Comment by angadhn** [comment]
@nozzington it looks like this branch is not upto date with my `main` branch; see image below which says you are 34 commits behind the `angadhn/SpacecraftDynamics:main`. So you will have to follow the instructions in [Contributing.md](https://github.com/angadhn/SpacecraftDynamics/blob/main/CONTRIBUTING.md#keeping-your-fork-updated), just to ensure your fork is updated.
image

**Comment by angadhn** [comment]
@nozzington Some minor changes/corrections to make from my review. A full sign-off will be from @thedukeofeelam.
- [ ] The square brackets could do with a slight increase in size. I forget the command but maybe it is `\big` or something. Check with GPT.
- [ ] This next part is not rendering correctly in the text:
image
The fix is to just have all of the items correlating to point 1 in the same cell. Otherwise I think html conversion gets messed up as the indentation levels are different.

- [ ] Maybe use a lighter shade of blue in the text below the image as the dark blue doesn't render nicely in dark mode. Or just go with default text for that one line of text about the semi-major axis.
image
- Remove the two explicit equations in point 4 and with the word Equations. The way you have set it up is great because the texts for (5) and (6) are in blue, meaning they are hyper links to the equation for the reader. We can save them trouble from reading repeated equations.
image
You have done this perfectly here:
image

**Comment by angadhn** [comment]
@nozzington also, please update author list to have Ilan's name after yours. Cheers.

**Comment by thedukeofeelam** [comment]
@nozzington 
Yup, I only picked up on this: Just put all of the content into 1 cell, it worked when I tried. 

image

For the brackets, GPT it, prompt something like: i give you equation, make brackets look nicer with **left and right commands**. Don't use the bigr and Bigr commands - it just doesn't work.

**Comment by nozzington** [comment]
@angadhn , @thedukeofeelam all points should have been addressed pls let me know!

**Comment by thedukeofeelam** [comment]
> @angadhn , @thedukeofeelam all points should have been addressed pls let me know!

I am checking now :)

**Review by angadhn — APPROVED** [review]
@nozzington this looks terrific. Love the effort and availability :-)

@thedukeofeelam love the pedantic review. Genuinely. This is how we push each other to the next level. Thanks!

**Pull request merged**
