### PR TITLE
Updated final reviewed Lecture 10 (review again)

### PR DESCRIPTION
**Pull request by Hardit-Saini**
updated lecture 10, please review again.

### CODE REVIEW

**Comment by thedukeofeelam** [comment]
1) Yellow - those numbering, did you want them to be that way? Oh nvm, I see it's based on that figure. Right. 
2) Green - I asked Noah to change things like cos i to cos(i), may be for the sake of consistency? I am being picky tho 

image

3) is that period necessary - again for consistency

image

4) "site" 

image

5) Would these two count as equations?

image

That's all I can see Harditty.

**Comment by thedukeofeelam** [comment]
Heading to sleep now, so wouldn't be able to review till tomorrow Hardit

**Comment by angadhn** [comment]
@Hardit-Saini One change to make is to add @thedukeofeelam in the author list after your name. If @Emma-airi has helped with the preparation of this file, then he should remain on the list, of course. If not, please feel free to remove him from the prepared by list.

@thedukeofeelam will double check the contents. On the surface it looks fine to me but I am not doing as close a review as he is. :-)

**Comment by thedukeofeelam** [comment]
Cutie pie @Hardit-Saini, let me know when you've made a new commit and I'll check through it again. Also, since I didn't even touch your ipynb, don't add my name love.

**Comment by Hardit-Saini** [comment]
> Cutie pie @Hardit-Saini, let me know when you've made a new commit and I'll check through it again. Also, since I didn't even touch your ipynb, don't add my name love.

Stop being weird. Also I sent a commit request maybe 10 times and it wasnt working so I figured the file needed a change and it sent. I was getting alot of weird errors in the form of infinite merging when doing [git merge main] so Im not fully sure if it actually merged so please let me know.

@angadhn @thedukeofeelam @Emma-airi

**Comment by thedukeofeelam** [comment]
> > Cutie pie @Hardit-Saini, let me know when you've made a new commit and I'll check through it again. Also, since I didn't even touch your ipynb, don't add my name love.
> 
> Stop being weird. Also I sent a commit request maybe 10 times and it wasnt working so I figured the file needed a change and it sent. I was getting alot of weird errors in the form of infinite merging when doing [git merge main] so Im not fully sure if it actually merged so please let me know.
> 
> @angadhn @thedukeofeelam @Emma-airi

Here's a pdf of your latest commit: [Time, Calendars and Launch Windows — My sample book.pdf](https://github.com/user-attachments/files/16917637/Time.Calendars.and.Launch.Windows.My.sample.book.pdf)
I am happy with the content + formatting. Think its good to go unless @angadhn has something to add.

**Comment by angadhn** [comment]
@Hardit-Saini only for this branch: I have just merged Noah's code so can you update your fork please? Thanks!

**Review by angadhn — APPROVED** [review]

**Comment by angadhn** [comment]
@Hardit-Saini this looks good. I have merged it but you will need to update the other PR as a result. Thanks for the effort here! Well done! :-)

**Comment by angadhn** [comment]
@Hardit-Saini this looks good. I have merged it but you will need to update the other PR as a result. Thanks for the effort here! Well done! :-)

**Pull request merged**
