### PR TITLE
Uploading Lecture 11 and it's images

### PR DESCRIPTION
**Pull request by mitanshc**
This is the first upload of Lecture 11 on it's own branch. I've made the changes which were required for Lecture 7. There is a little python thing I did, which may or may not look weird on publish.

### CODE REVIEW

**Comment by mitanshc** [comment]
Honestly not sure what happened here. It failed the check like Lecture 12 right now. I fiddled around and kept updating and it passed somehow.

**Comment by angadhn** [comment]
@mitanshc sorry- it has taken me a while to get to this PR. Working on it today. As an aside, have you gotten a local building of Jupyter books working for yourself? More on that here for windows: https://jupyterbook.org/en/stable/advanced/windows.html

**Comment by angadhn** [comment]
@mitanshc first change: please rename the file to `Lecture11`. Currently it has a whitespace between the Lecture and 11.

**Comment by angadhn** [comment]
@mitanshc please use `^\circ` instead of `degree` for the angles.

**Comment by angadhn** [comment]
I think your perturbation plots are great.

1. Can you remove the stuff before import statements in the below:
image

2. Can you add some justification on why y1, y2, y3, y4 equations are what they are or how you got these functions? Add these lines to after the plot is generated. Thanks!

**Comment by mitanshc** [comment]
> @mitanshc sorry- it has taken me a while to get to this PR. Working on it today. As an aside, have you gotten a local building of Jupyter books working for yourself? More on that here for windows: https://jupyterbook.org/en/stable/advanced/windows.html

I used to have one through Anaconda. I’ve since reset my PC and I’ve been using the main Python along with VSCode. Would you recommend Jupyterbooks over this?

**Comment by angadhn** [comment]
> > @mitanshc sorry- it has taken me a while to get to this PR. Working on it today. As an aside, have you gotten a local building of Jupyter books working for yourself? More on that here for windows: https://jupyterbook.org/en/stable/advanced/windows.html
> 
> I used to have one through Anaconda. I’ve since reset my PC and I’ve been using the main Python along with VSCode. Would you recommend Jupyterbooks over this?

No- it's okay. Stick with what you have for now. Sorry for confusing you about this. But let's have a talk about this another time in the context of your project. Note that, especially in your case, I would seriously consider getting a virtual machine of Linux running on your computer. Or a dual boot of Linux, if you are confident at setting that up. again, we can discuss this later.

**Comment by mitanshc** [comment]
Hello,
I got caught up in my video and only made a few edits for demonstration purposes. I didn’t  get around to fixing the code section of the lecture and I just caught a couple more \degree in my markdown. Thought I had a look on the live website and it doesn’t seem noticeable on a phone. 
Would you like me to make those edits on a separate branch but keep the file names and everything the same and create a new PR?

On a side note, I managed to get Jupyter-books working to build a book. Though I haven’t got round to editing the beyond the title.

**Comment by angadhn** [comment]
All good- I fixed up the little issues with the degrees signs myself. Thanks for working on the video. Very helpful!

**Pull request merged**
