### PR TITLE
Changing attitude section to be the same as the completed section in EMS418 on the same topic.

### PR DESCRIPTION
**Pull request by Joosty**
Changing the attitude section to be the same as the identical transcribed/edited section in the EMS418U textbook. Made tiny edits to add content and authors and fix a couple of errors. Like before the single kinetics file has been broken up into 3 smaller files and placed in the relevant directory. You will probably have to make changes to the jupyterbook toc to account for this.

Since the current version is just the raw notes I think this is worth adding in as the work was mostly already done.

Have future pages coming for attitude that will be a separate PR.

### CODE REVIEW

**Comment by angadhn** [comment]
@Joosty I'll take a look at this next week- apologies for the delay!

**Comment by angadhn** [comment]
@Joosty can you update your PR and then I will revisit this on the weekend? Thanks!

**Comment by Joosty** [comment]
@angadhn Sorry, I saw this but totally forgot to actually sync it. It is done now :/

**Comment by angadhn** [comment]
Cheers @Joosty. I merged for now as I am short on time for a thorough review- will come back to you if needed. Thanks!

**Comment by angadhn** [comment]
I see there are 3 ipynb files- without my having to open, can you just summarise what each is about? And in what order they might appear in  the toc?

**Comment by angadhn** [comment]
Hmmm- okay. That explains why they aren't auto-building. Possibly some conflicts in equations but no big deal. We deal with this at a later date. Appreciate the initiative.

**Pull request merged**
