### PR TITLE
Add CODEOWNERS file

### PR DESCRIPTION
**Pull request by angadhn**
This is so only I should be able to merge PRs.

### CODE REVIEW

**Comment by angadhn** [comment]
@angadhn can you review this?

**Comment by angadhn** [comment]
@thedukeofeelam can you just come on board and sign off on this? Trialling something new.

**Comment by angadhn** [comment]
@mitanshc do you still see the option to merge PRs now?

**Comment by mitanshc** [comment]
I can’t see the merge option, though now I have to add my review for the pull request to go through? Unless you can override that.

**Comment by Emma-airi** [comment]
I have reviewed and it looks brilliant.

**Review by mitanshc — APPROVED** [review]
This is the said review.

**Comment by mitanshc** [comment]
Ah, if I go into add review. Then “approve” it on my end” I can come back to this page then merge if I wanted to.

**Review by Emma-airi — APPROVED** [review]
Looks good again

**Comment by angadhn** [comment]
Thanks @mitanshc and @Emma-airi.

**Pull request merged**
