### PR TITLE
Lecture 5

### PR DESCRIPTION
**Pull request by thedukeofeelam**
Pull Request for my Lecture 5. Contains 1 ipynb and 7 png files.

### CODE REVIEW

**Comment by angadhn** [comment]
@Joosty can you help review this PR?

You could do this on here using ReviewNB but I now feel the below approach is better.

1. clone the repository
2. fetch this pr (using Pr number) as a branch. For example, in this case it would be using the number 11:
```
git fetch origin pull/11/head:pr-11
```
3. then checkout the branch.
4. build the book locally and take a look at the output.

**Comment by Joosty** [comment]
Happy to, will start this evening and get back when I have some comments :)

**Comment by Joosty** [comment]
Issue 1: Images not loading 

image

When I build the book images do not seem to be loading. I have looked in the ipynb file and see that the paths may not be fully set up. I have gone ahead and fixed this in my own version using the code below. **While this is recognised in VSCode it still does not seem to load when the book is built.** Will continue looking for a way to fix this. 


`<div style="text-align: center;">
    Figure 5.1
    <p><strong>Figure 5.1:</strong> Illustration of an orbital path in polar coordinates showing the radial and tangential components of velocity. The angle marked \(\gamma\) is the flight path angle; the angle between the tangential component and the resultant velocity vector.
    </p>
</div>`

**Comment by angadhn** [comment]
@Joosty Your task is only to review- not make fixes :-)

**Comment by Joosty** [comment]
**Issue 2: \degree not rendering**

The '\degree' method does not appear to be working. The best way of doing this is simply directly using the symbol  ----> °

image

**Comment by angadhn** [comment]
> **Issue 2: \degree not rendering**
> 
> 
> 
> The '\degree' method does not appear to be working. The best way of doing this is simply directly using the symbol  ----> °
> 
> 
> 
> image
> 
> 

Actually `^\circ` is better $^\circ$.

**Comment by Joosty** [comment]
**Issue 3: Misc text issues**

1. Some brackets could be made to look nicer by using '\left[' and '\right]' in place of '\bigr' etc. Example: `\left[\frac{-p}{u^2}\right]`. Issue shown below:
image

2. '\ref' not working correctly. 
image

3. Caption not rendering correctly
image

4. Unnessicary use of arrows on top of vectors, when I have spoken with @angadhn using \mathbf or \bf with no arrow is desired.
image

A lot of these issues crop up across the file a few times so keep an eye out. If I see any other issues I will comment. Cheers and I hope this was helpful.

**Comment by angadhn** [comment]
> **Issue 3: Misc text issues**
> 
> 
> 
> 1. Some brackets could be made to look nicer by using '\left[' and '\right]' in place of '\bigr' etc. Example: `\left[\frac{-p}{u^2}\right]`. Issue shown below:
> 
> image
> 
> 
> 
> 2. '\ref' not working correctly. 
> 
> image
> 
> 
> 
> 3. Caption not rendering correctly
> 
> image
> 
> 
> 
> 4. Unnessicary use of arrows on top of vectors, when I have spoken with @angadhn using \mathbf or \bf with no arrow is desired.
> 
> image
> 
> 
> 
> A lot of these issues crop up across the file a few times so keep an eye out. If I see any other issues I will comment. Cheers and I hope this was helpful.
> 
> 

Brilliant review!

**Comment by thedukeofeelam** [comment]
> **Issue 3: Misc text issues**
> 
> 1. Some brackets could be made to look nicer by using '\left[' and '\right]' in place of '\bigr' etc. Example: `\left[\frac{-p}{u^2}\right]`. Issue shown below:
>    image
> 2. '\ref' not working correctly.
>    image
> 3. Caption not rendering correctly
>    image
> 4. Unnessicary use of arrows on top of vectors, when I have spoken with @angadhn using \mathbf or \bf with no arrow is desired.
>    image
> 
> A lot of these issues crop up across the file a few times so keep an eye out. If I see any other issues I will comment. Cheers and I hope this was helpful.

Thank you for all your support with this, I will try resolve them over the weekend!

**Comment by Joosty** [comment]
Just had a brief look over it, on first glance the images are not working still - maybe worth building yourself to check if this is working.

In the past, I have used the method shown in the screenshot to import the images. This involves giving the path to the image in question. This may be worth a try.
![image](https://github.com/user-attachments/assets/a34674f3-adb1-4c7d-a625-ba38d87e09a7

I'll follow up if I find any other issues.

Cheers,
Joost

**Comment by angadhn** [comment]
Thanks again for your efforts, @thedukeofeelam and @Joosty. You can see the pages over [here](
https://www.angadhn.com/SpacecraftDynamics/orbital-mechanics/Lecture5/Lecture5.html) for this PR and the fruits of your labour!

**Comment by angadhn** [comment]
@Joosty just adding you in the reviewer list so we have a formal trail of your being involved for good measure. A bit late with doing that- sorry.

**Review by Joosty — COMMENTED** [review]
All good.

**Pull request merged**
