### PR TITLE
PS1 Fix

### PR DESCRIPTION
**Pull request by adrulpz**
Hi, the problem is apparently just with the equation using  $$ for a block... so I added more cells XD, and that should be fine just for better-looking equations with actual space between them.

### CODE REVIEW

**Comment by angadhn** [comment]
@adrulpz you do not actually have the most up to date version of my `master`. You can see that both your `master` and `PS1_Fix`; for example, your `PS1_Fix` branch is 154 commits behind my `master`.
image

In fact, even your `master` is behind mine baby the same number. So you need to first update your `master` and then your `PS1_Fix`. push changes from both to GitHub. This is the process. The specifics on how to do all this at the command line? Glad you asked! This can be found [here](https://github.com/angadhn/SpacecraftDynamics/blob/main/CONTRIBUTING.md#keeping-your-fork-updated).

Maybe @Joosty can help here too, if/when he has time- pretty please.

**Comment by Joosty** [comment]
Happy to help. @adrulpz  I would suggest just clicking this sync button in the GitHub website shown in my screenshot below.

image

If this doesn't work then please let me know! 

Cheers

**Comment by adrulpz** [comment]
I thought I had pushed that button, but maybe I just didn't and didn't check later. Thanks! I'll let you know

**Comment by adrulpz** [comment]
So... I think what happened is that I synchronised the changes with the button in the main branch after creating the fix branch because I aborted the merging on the terminal 😅. Anyway, I believe everything has been updated. If not, would it be better if I started over again, creating another branch?

**Review by Joosty — CHANGES_REQUESTED** [review]
Happy with the changes to the PS1.ipynb file, the equations and formatting errors look much better. 

I am a bit confused as to why there are a few additional files now (namely **vector.ipynb in lecture 101** and **PS1-checkpoint.ipynb in .ipynb-checkpoints**) . These are circled in the image below. Are these meant to be here or is this an impact of the weird sync stuff?

cheers

image

**Comment by angadhn** [comment]
@Joosty I believe this 101 file is from the tutorial.

@adrulpz can you please delete that and the entire directory .ipynb_checkpoints please? Then commit and push.

**Comment by adrulpz** [comment]
Done :) 
thanks for reviewing it  and for the guidance @Joosty

**Review by angadhn — APPROVED** [review]

**Review by angadhn — APPROVED** [review]

**Pull request merged**
