### PR TITLE
Lecture6

### PR DESCRIPTION
**Pull request by nozzington**
hopefully I have done this correctly, this should be the updated file for Lecture 6 with the vectors in boldface and subscripts in normal.

### CODE REVIEW

**Comment by angadhn** [comment]
@thedukeofeelam can you please help review this PR?

**Comment by thedukeofeelam** [comment]
@nozzington 

7) Some of the brackets could also be made nicer - especially in the longer equations. 
image
I asked ChatGPT to make this equation nicer (by using the left and right commands for the brackets) and its code renders the equation this way:
image

**Comment by thedukeofeelam** [comment]
@nozzington 

Just built your book on html and I see this:

image

You have used double dollars to make it an equation but it renders it on the same line ignoring a dollar sign on either side. Maybe put them on a new line? and try with a double dollar? Perhaps something like this:

image

**Comment by angadhn** [comment]
@thedukeofeelam are all your comments addressed?

**Comment by thedukeofeelam** [comment]
> @thedukeofeelam are all your comments addressed?

Just woke up, will check and let you know asap. Same for the other lecture.

**Comment by thedukeofeelam** [comment]
@nozzington, again see PDF for this lecture as to how it gets rendered on a HTML page. See comments on the PDF too + carry on making the updates from yesterday's review. 

[Lecture 6.pdf](https://github.com/user-attachments/files/16868484/Lecture.6.pdf)

@angadhn, Noah is still working on making the updates.

**Comment by nozzington** [comment]
should be ready, tell me if there arer any of the points i have missed or if anything doesn't work

**Comment by thedukeofeelam** [comment]
I will take a look at both the lectures again and will update :) Thanks Noah.

**Comment by thedukeofeelam** [comment]
1) Typo here means your content table hyperlink isn't functional for that section. 

image

2) Spaces after colons in major equations. Leave a single space after colon. 

image

3)  The blue and red are very similar in formatting. But if you look at the code cells, in the top one, commands like \geq are not recognised (not in blue), I'd say rewrite it till both the red and blue sections render the same way on ipynb. 

image

4) Similar issue with this orange section of code:

image

Looking at how it has been coded: You've almost coded it as a major equation with the weird maths stuff, but without the label part to it. So if its not a major equation, go with $$. 

image

5) Similar issue: Maybe have these enclosed in $$ instead of the mathing stuff. 

image

6) Finally, when you reference equations from your previous lecture, my HTML doesn't seem to pick up the references. I don't know if it will be replicated in the final textbook - so I mean it's better if you just name the equation like "recall the vis viva equation" and dont use reference L3_10, does that make sense? 

image

**Comment by nozzington** [comment]
I have addressed each of the points, let me know if there's anything else!

**Comment by thedukeofeelam** [comment]
These comments only apply to this lecture: 

1) Add a space after the period in all 4 elements.  

image

2) This section gets rendered this way

image

Maybe add a space after your text and then $$ equation here $$.

image

3) Fix alignment as necessary in the first and last sections

image

image

@nozzington

**Comment by nozzington** [comment]
Great, thank you, will get to it this eve

**Comment by nozzington** [comment]
@thedukeofeelam hopefully fixed all the issues!

**Comment by thedukeofeelam** [comment]
@nozzington 

This lecture looks fine to me. Except these two really tiny points. 
Some trigs don't have brackets, I am pretty sure I checked all of them, but there's still a few here.

**Comment by nozzington** [comment]
@thedukeofeelam just addressed it hopefully it's okay, will be free in evening after now to fix if so

**Comment by thedukeofeelam** [comment]
> @thedukeofeelam just addressed it hopefully it's okay, will be free in evening after now to fix if so

im on it now

**Comment by angadhn** [comment]
@nozzington might need another update of your fork as per contributing to get your other merged PR in here.

**Comment by nozzington** [comment]
@angadhn of course, will do that quickly now

**Comment by thedukeofeelam** [comment]
I think we are good to go with this

**Comment by nozzington** [comment]
@angadhn it says everything is up to date on this branch on my end and that a merge is possible

**Comment by angadhn** [comment]
@nozzington just checked. It isn't updated. Maybe you are on the wrong branch? :-)

image

**Comment by nozzington** [comment]
@angadhn 

For me it says the checks are all passed and when I tried to update on my local it said everything was up to date? Maybe there's a lag on my end with the lecture 3 merge

**Comment by angadhn** [comment]
@nozzington I see that too and it is likely missing something- because I wrote it so it must be wrong (with GPT, of course). Not sure why. But I can assure you it is not up to date. When you get the moment, just run the commands in:

https://github.com/angadhn/SpacecraftDynamics/blob/main/CONTRIBUTING.md#keeping-your-fork-updated

**Comment by angadhn** [comment]
@nozzington basically, I just merged your Lecture 3 PR. That affects the git commit history. This new addition of Lecture 3 is not in your local `Lecture6` branch. Once it is, you need to push this back to GitHub.

**Comment by nozzington** [comment]
@angadhn okay, will do, will message again if I get it to work!

**Comment by nozzington** [comment]
it's really not working on my end, it keeps telling me everything is up to date, I have checked with chatgpt, refreshed dozens of times, but it keeps telling me everything is okay. i am on the right branch, I am fetching from the right place, I really don't know what I can do

**Comment by nozzington** [comment]
@angadhn it should now be updated, following the instructions!

**Review by angadhn — APPROVED** [review]

**Comment by angadhn** [comment]
> @angadhn it should now be updated, following the instructions!

Thanks! All done!

**Comment by thedukeofeelam** [comment]
> > @angadhn it should now be updated, following the instructions!
> 
> Thanks! All done!

Just realised we can't find this lecture on the textbook? 
https://www.angadhn.com/SpacecraftDynamics/orbital-mechanics/Lecture1/vector.html

**Comment by angadhn** [comment]
@thedukeofeelam whoops- good catch! Should be up now!

**Comment by angadhn** [comment]
@nozzington Just realised in this review, that there are no images; any reason for them to not be included?

**Comment by angadhn** [comment]
@nozzington in fact, comparing to the notes, I see there's a lot of stuff missing in the submitted ipynb file.

**Pull request merged**
